### ISSUE TITLE
matchAppRun() error

### ISSUE THREAD

**Issue by jkaddis** [avucoh/DIVE#8]
I ran above command and came across this error:

Warning: Error in value[[3L]]: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'typedarray-0.1'; `directoryPath` = '/home/avu/R/x86_64-pc-linux-gnu-library/3.4/plotly/htmlwidgets/lib/typedarray'
  [No stack trace available]

**Comment by avucoh** [comment]
So this seems to be the same issue as described here: 

https://stackoverflow.com/questions/54137896/an-absolute-package-path-is-set-for-the-plotly-package-upon-installation-of-anot

So there are two options:
1) store plotly dependencies in the package itself and modify plotly cached object in the hacky way as described in the StackOverflow answer?
2) don't have cached object -- just render it, and the paths will be correct for each new environment

I'm going with option #2

**Comment by jkaddis** [comment]
I agree.  Thanks.
